
server:
  port: 8083
spring:
  application:
    name: cart-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9991/eureka/,http://localhost:9992/eureka/
feign:
  hystrix:
    enabled: true